namespace Synergy.CRM.Models.Opportunity
{
    public enum OpportunityHistoryFieldName
    {
        BorrowerName = 1,
        BorrowerSSN,
        BorrowerEmail,
        BorrowerCellPhone,
        BorrowerWorkPhone,
        BorrowerFax,
        BorrowerMarialStatus,
        BorrowerDateOfBirth,
        BorrowerTitle,
        BorrowerEntityName,
        BorrowerTaxIdNumber,
        CloseDate,
        CloseProbabilityPercent,
        Stage,
        LoanType,
        OriginationPercent,
        ClosingCost,
        LenderCredit,
        AmountDue,
        InterestRate,
        Term,
        PrePay,
        MonthlyPrepay,
        PercentagePrepay,
        CurrentLoanBalance,
        ThirdPartyLoanBalance,
        PropertyType,
        PropertyAddress,
        PrimaryContactName,
    }
}